import Head from 'next/head'
import { Contacts } from '../components/sections/about/Contacts'
import { Informative } from '../components/sections/about/Informative'
import { AboutFront } from './../components/sections/about/AboutFront'

export default function About() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />

      <link
        rel="icon"
        href="/favicon.ico"
      />
    </Head>
    
    <main>
      <AboutFront />
      <div className='about-section'>
        <Informative />
        <Contacts />
      </div>
    </main>
    </>
  )
}
