import Head from 'next/head'
import { ClubQuestions } from '../components/sections/home/ClubQuestions'
import { HomeFront } from '../components/sections/home/HomeFront'
import { HeadingToggler } from '../components/utils/HeadingToggler'

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />

      <link
        rel="icon"
        href="/favicon.ico"
      />
    </Head>
    
    <main>
      <HomeFront />
      <ClubQuestions />
      <HeadingToggler heading='UPCOMING EVENTS' />
    </main>
    </>
  )
}
