import Head from 'next/head'
import { HomeFront } from '../components/sections/home/HomeFront'
import { BottomCTA } from '../components/sections/home/BottomCTA'
import { ClubAbout } from '../components/sections/home/ClubAbout'
import { ClubQuestions } from '../components/sections/home/ClubQuestions'
import { Quote } from '../components/sections/home/Quote'
import { UpcomingEvents } from '../components/sections/home/UpcomingEvents'

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />

      <link
        rel="icon"
        href="/favicon.ico"
      />
    </Head>
    
    <main>
      <HomeFront />
      <ClubQuestions />
      <UpcomingEvents />
      <ClubAbout />
      <Quote />
      <BottomCTA />
    </main>
    </>
  )
}
